/** Carta de 50 linhas — de David para Samarah. */
export const LETTER_LINES: string[] = [
  "Samarah, hoje é Dia das Crianças, e eu pensei em você antes de abrir os olhos.",
  "Não porque o calendário mandou. Porque cada dia em que você existe já parece um presente.",
  "Desde o dia 7 de novembro de 2025, o mundo tem outro relógio.",
  "O meu passa por você.",
  "Eu conto os anos, os meses, os dias. Os minutos. Os segundos.",
  "E nenhum deles é pequeno demais para caber saudade.",
  "Você chegou quieta e virou o centro de tudo.",
  "Não pediu palco. Não pediu barulho. Só ficou — e o resto do mundo aprendeu a orbitar.",
  "Eu gosto da sua risada quando ela escapa sem aviso.",
  "Gosto do jeito que você fala de coisas simples como se fossem tesouro.",
  "Gosto de como você é forte e, ao mesmo tempo, tão delicada.",
  "Tem dias em que a distância pesa no peito.",
  "Tem noites em que o silêncio parece maior do que o quarto.",
  "Aí eu lembro do seu nome — Samarah — e a escuridão recua um pouco.",
  "A gente ainda não se encontrou do jeito que o coração pede.",
  "Mas já se encontrou de todos os outros: na conversa, na espera, na fé.",
  "Eu guardo dezembro de 2027 como quem guarda um segredo bom.",
  "As férias vão abrir a porta que o tempo inteiro deixou entreaberta.",
  "Eu vou te ver.",
  "E o tempo, que agora é número nesta página, vira abraço.",
  "Até lá, eu escolho você todos os dias.",
  "Escolho a paciência. Escolho a promessa. Escolho não desistir da gente.",
  "Você merece leveza.",
  "Merece alguém que lembre da sua data, da sua voz, do seu jeito.",
  "Merece um amor que não apresse e não some.",
  "Se eu pudesse, te mandaria o céu de outubro numa caixa.",
  "Como não posso, te mando esta carta.",
  "Cinquenta linhas, e ainda assim insuficiente.",
  "Porque você não cabe em papel.",
  "Cabe em mim.",
  "Eu espero dezembro de 2027 com o coração na ponta dos pés.",
  "Espero o instante em que o oi deixar de ser tela e virar presença.",
  "Espero sua mão. Espero o silêncio bom de quem finalmente chegou.",
  "Até lá, deixa eu te dizer o que importa:",
  "eu gosto de você.",
  "Gosto de verdade.",
  "Gosto no meio da semana, no fim da madrugada, no começo de qualquer coisa.",
  "Gosto quando a saudade aperta e quando ela alivia.",
  "Gosto de construir isso com cuidado, no nosso ritmo.",
  "Feliz Dia das Crianças, Samarah.",
  "Que o mundo seja gentil com você.",
  "Que seus sonhos tenham coragem.",
  "Que o nosso encontro em dezembro de 2027 venha inteiro, sem pressa e sem falta.",
  "Eu estarei lá.",
  "Com o mesmo coração de 7 de novembro.",
  "Só que maior — porque você o fez crescer.",
  "Te espero.",
  "Te escolho.",
  "Te amo no silêncio e no anúncio.",
  "Para você, Samarah, hoje e em todos os segundos que este relógio ainda vai contar.",
];
